shadowVer=9.4.1
paperApiVersion=26.2.build.84-stable
paperBuild=84
paperChannel=STABLE
paperJarName=Paper-26.2.jar
paperJarSha256=defe82c1c89067186895de34cf32983e9f5a2ea387cfe7597c020faebb98ca16
packetEventsVersion=2.13.0
adventureNbtVersion=5.2.0
pluginVersion=14.0.1
pluginBuild=007
paperTarget=26.2
javaTarget=25
buildJdkVersion=25.0.4
runtimeJdk25Version=25.0.4
runtimeJdk26Version=26.0.2

org.gradle.caching=true
org.gradle.configuration-cache=true
